export const SESSIONS_STATS = [
  { label: 'Total Webinars', value: '24', growth: '+12.5%', isPositive: true },
  { label: 'Cohort Program', value: '12', growth: '+12.5%', isPositive: true },
  { label: 'Mentorship Program', value: '2', growth: '+12.5%', isPositive: true },
];

export const MOCK_SESSIONS = [
  {
    id: "3443345345",
    title: "Importance of Medical Ethics",
    description: "It focuses on patient care and moral re...",
    type: "Webinar",
    status: "Active",
    deadline: "14-01-2026",
  },
  {
    id: "3443345345",
    title: "Importance of Medical Ethics",
    description: "It focuses on patient care and moral re...",
    type: "Cohort",
    status: "Completed",
    deadline: "14-01-2026",
  },
  {
    id: "3443345345",
    title: "Autonomy respects a patient's right",
    description: "It focuses on patient care and moral re...",
    type: "Webinar",
    status: "Active",
    deadline: "14-01-2026",
  },
  {
    id: "3443345345",
    title: 'Non-maleficence means "do no harm."',
    description: "It focuses on patient care and moral re...",
    type: "Cohort",
    status: "Active",
    deadline: "14-01-2026",
  },
  {
    id: "3443345345",
    title: "Importance of Medical Ethics",
    description: "It focuses on patient care and moral re...",
    type: "Webinar",
    status: "Active",
    deadline: "14-01-2026",
  },
  {
    id: "3443345345",
    title: "Importance of Medical Ethics",
    description: "It focuses on patient care and moral re...",
    type: "Webinar",
    status: "Active",
    deadline: "14-01-2026",
  },
  {
    id: "3443345345",
    title: "Importance of Medical Ethics",
    description: "It focuses on patient care and moral re...",
    type: "Cohort",
    status: "Completed",
    deadline: "14-01-2026",
  },
  {
    id: "3443345345",
    title: "Importance of Medical Ethics",
    description: "It focuses on patient care and moral re...",
    type: "Webinar",
    status: "Completed",
    deadline: "14-01-2026",
  },
  {
    id: "3443345345",
    title: "Importance of Medical Ethics",
    description: "It focuses on patient care and moral re...",
    type: "Cohort",
    status: "Completed",
    deadline: "14-01-2026",
  },
];
