import { Assignment } from './types';

export const assignmentData: Assignment[] = [
  {
    id: '1',
    assignmentId: 'ASIGN-2024',
    sessionTitle: 'Thesis Chapter 3 - Literature I...',
    studentName: 'Pradhyumn Dhondi',
    sessionType: 'Webinar',
    dueDate: '15 Jan 2024',
    status: 'Submitted',
    submissionDate: '22 Jan 2024',
    hasDownload: true,
  },
  {
    id: '2',
    assignmentId: 'ASIGN-2024',
    sessionTitle: 'Research Paper Draft - Social',
    studentName: 'Pradhyumn Dhondi',
    sessionType: 'Cohort',
    dueDate: '15 Jan 2024',
    status: 'Pending',
    submissionDate: '22 Jan 2024',
    hasDownload: false,
  },
  {
    id: '3',
    assignmentId: 'ASIGN-2024',
    sessionTitle: 'Career Strategy Session - Phd',
    studentName: 'Pradhyumn Dhondi',
    sessionType: 'Mentorship',
    dueDate: '15 Jan 2024',
    status: 'Review Done',
    submissionDate: '22 Jan 2024',
    hasDownload: true,
  },
  {
    id: '4',
    assignmentId: 'ASIGN-2024',
    sessionTitle: 'Academic Writing Masterclass',
    studentName: 'Pradhyumn Dhondi',
    sessionType: 'Cohort',
    dueDate: '15 Jan 2024',
    status: 'Pending',
    submissionDate: '22 Jan 2024',
    hasDownload: true,
  },
  {
    id: '5',
    assignmentId: 'ASIGN-2024',
    sessionTitle: 'MBA Application Essay - Busir',
    studentName: 'Pradhyumn Dhondi',
    sessionType: 'Mentorship',
    dueDate: '15 Jan 2024',
    status: 'Pending',
    submissionDate: '22 Jan 2024',
    hasDownload: false,
  },
  {
    id: '6',
    assignmentId: 'ASIGN-2024',
    sessionTitle: 'Thesis Chapter 3 - Literature I...',
    studentName: 'Pradhyumn Dhondi',
    sessionType: 'Webinar',
    dueDate: '15 Jan 2024',
    status: 'Review Done',
    submissionDate: '22 Jan 2024',
    hasDownload: true,
  },
  {
    id: '7',
    assignmentId: 'ASIGN-2024',
    sessionTitle: 'Literature Survey - Climate Ch',
    studentName: 'Pradhyumn Dhondi',
    sessionType: 'Webinar',
    dueDate: '15 Jan 2024',
    status: 'Review Done',
    submissionDate: '22 Jan 2024',
    hasDownload: true,
  },
  {
    id: '8',
    assignmentId: 'ASIGN-2024',
    sessionTitle: 'PhD Guidance Session - Disse',
    studentName: 'Pradhyumn Dhondi',
    sessionType: 'Mentorship',
    dueDate: '15 Jan 2024',
    status: 'Submitted',
    submissionDate: '22 Jan 2024',
    hasDownload: true,
  },
  {
    id: '9',
    assignmentId: 'ASIGN-2024',
    sessionTitle: 'Statistics for Research - SPSS',
    studentName: 'Pradhyumn Dhondi',
    sessionType: 'Webinar',
    dueDate: '15 Jan 2024',
    status: 'Review Done',
    submissionDate: '22 Jan 2024',
    hasDownload: true,
  },
  {
    id: '10',
    assignmentId: 'ASIGN-2024',
    sessionTitle: 'Thesis Chapter 3 - Literature I',
    studentName: 'Pradhyumn Dhondi',
    sessionType: 'Webinar',
    dueDate: '15 Jan 2024',
    status: 'Pending',
    submissionDate: '22 Jan 2024',
    hasDownload: false,
  },
];
