import {
  Shield,
  BookOpen,
  User as UserIcon,
  Edit2,
  Building2,
  Languages,
} from "lucide-react";
import { User } from "./types";

export const permissionsRoles = [
  {
    role: "Admin",
    users: 2,
    iconColor: "text-red-500",
    bgColor: "bg-red-50",
    Icon: Shield,
    permissions: [true, true, true, true, true, true],
  },
  {
    role: "Educator",
    users: 4,
    iconColor: "text-purple-500",
    bgColor: "bg-purple-50",
    Icon: BookOpen,
    permissions: [false, true, true, true, false, false],
  },
  {
    role: "Student",
    users: 5,
    iconColor: "text-blue-500",
    bgColor: "bg-blue-50",
    Icon: UserIcon,
    permissions: [false, false, false, false, false, false],
  },
  {
    role: "Editor",
    users: 1,
    iconColor: "text-yellow-500",
    bgColor: "bg-yellow-50",
    Icon: Edit2,
    permissions: [false, false, true, false, false, false],
  },
  {
    role: "Institution",
    users: 1,
    iconColor: "text-indigo-500",
    bgColor: "bg-indigo-50",
    Icon: Building2,
    permissions: [true, true, false, true, true, false],
  },
  {
    role: "Translator",
    users: 1,
    iconColor: "text-teal-500",
    bgColor: "bg-teal-50",
    Icon: Languages,
    permissions: [false, false, false, false, false, false],
  },
];

export const usersData: User[] = [
  {
    id: "USR-001",
    name: "Priya Sharma",
    email: "priya.s@email.com",
    role: "Student",
    status: "Active",
    joined: "Jan 15, 2024",
    sessions: 5,
  },
  {
    id: "USR-002",
    name: "Dr. Sarah Chen",
    email: "sarah.c@email.com",
    role: "Educator",
    status: "Active",
    joined: "Nov 5, 2023",
    sessions: 124,
  },
  {
    id: "USR-003",
    name: "Rahul Kumar",
    email: "rahul.k@email.com",
    role: "Student",
    status: "Active",
    joined: "Feb 2, 2024",
    sessions: 2,
  },
  {
    id: "USR-004",
    name: "Prof. James Wilson",
    email: "james.w@email.com",
    role: "Educator",
    status: "Active",
    joined: "Sep 10, 2023",
    sessions: 186,
  },
  {
    id: "USR-005",
    name: "Neha Gupta",
    email: "neha.g@email.com",
    role: "Student",
    status: "Suspended",
    joined: "Dec 1, 2023",
    sessions: 12,
  },
  {
    id: "USR-006",
    name: "Aisha Muhammad",
    email: "aisha.m@email.com",
    role: "Student",
    status: "Active",
    joined: "Jan 5, 2024",
    sessions: 3,
  },
  {
    id: "USR-007",
    name: "Dr. Lin Wu",
    email: "lin.w@email.com",
    role: "Educator",
    status: "Active",
    joined: "Jul 22, 2023",
    sessions: 89,
  },
  {
    id: "USR-008",
    name: "Chen Meng",
    email: "chen.m@email.com",
    role: "Student",
    status: "Active",
    joined: "Feb 18, 2024",
    sessions: 7,
  },
];
